# Generated by Django 4.2.7 on 2024-02-16 12:24

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Option",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_ad", models.DateTimeField(auto_now_add=True)),
                ("update_ad", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=64)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("Button", "Button"),
                            ("Select", "Select"),
                            ("Text", "Text"),
                            ("Number", "Number"),
                            ("Multiple choice", "Multiple Choice"),
                        ],
                        max_length=64,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
