# Generated by Django 4.2.7 on 2024-02-19 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Option",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_ad", models.DateTimeField(auto_now_add=True)),
                ("update_ad", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=64)),
                (
                    "option_type",
                    models.CharField(
                        choices=[
                            ("Button", "Button"),
                            ("Select", "Select"),
                            ("Text", "Text"),
                            ("Number", "Number"),
                            ("Multiple choice", "Multiple Choice"),
                        ],
                        max_length=64,
                    ),
                ),
                ("order", models.IntegerField(default=0)),
                ("placeholder", models.CharField(blank=True, max_length=64, null=True)),
                ("required", models.BooleanField(default=False)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="OptionValue",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_ad", models.DateTimeField(auto_now_add=True)),
                ("update_ad", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=128)),
                ("order", models.IntegerField(default=0)),
                (
                    "option",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="option", to="options.option"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
