# Generated by Django 4.2.7 on 2024-02-19 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("olx", "0003_plan_plandetailgroup_planprice_plandetail_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Complaint",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_ad", models.DateTimeField(auto_now_add=True)),
                ("update_ad", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=128)),
                ("description", models.TextField()),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PlanDetailPrice",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_ad", models.DateTimeField(auto_now_add=True)),
                ("update_ad", models.DateTimeField(auto_now=True)),
                ("price", models.IntegerField()),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="detail_category", to="olx.category"
                    ),
                ),
                (
                    "plan_detail",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="plan_details", to="olx.plandetail"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
